modules:
    - imsim

template: imsim-config-instcat

# Set all of the entries needed to simulate ComCam instead of LSSTCam

input.tree_rings.file_name: LsstComCamSim_tree_rings_2024-02-03.txt
input.vignetting.file_name: LSSTComCamSim_vignetting_data.json
input.telescope:
    file_name:
        type: FormattedStr
        format: ComCam_%s.yaml
        items:
            - "$band"
    rotTelPos:
        type: Degrees
        theta: { type: OpsimData, field: rotTelPos }
    camera: "@output.camera"

output.camera: LsstComCamSim
output.det_num.first: 0
output.nfiles: 9
output.readout.bias_levels_file: LSSTComCamSim_bias_levels.json
