
# Use imSim custom modules
modules:
    - imsim

# Get most of the configuration from the imSim named template
template: imsim-config

# Note: by default these config files assome that you have set the enviroment
# variable SIMS_SED_LIBRARY_DIR for the location of the astrophysical SEDs.
#
# You can find the SEDS at NERSC at:
# /cvmfs/sw.lsst.eu/linux-x86_64/lsst_sims/sims_w_2020_28/stack/current/Linux64/sims_sed_library/2017.01.24-1-g5b328a8
#
# and on OSX if you use CVMFS at (last pinned version of lsst_sims)
# /cvmfs/sw.lsst.eu/darwin-x86_64/lsst_sims/sims_w_2020_15/stack/current/DarwinX86/sims_sed_library/2017.01.24
#
# You can also supply a local directory for the SEDs by overriding the sed_dir variable.
#
# You can also override any of the config variables on the command line.  For
# example:
#
# galsim imsim-user.yaml input.instance_catalog.file_name=00466749/cat_466749.txt
#
# Overide the the values in the template configuration with the values below.

# Here are examples of local parameters you might change for your simulation.
input.instance_catalog.file_name: ../tests/data/tiny_instcat.txt
input.instance_catalog.sed_dir: $os.environ.get('SIMS_SED_LIBRARY_DIR') # current default
input.instance_catalog.sort_mag: False

# Our tiny instance catalog only uses one det, so save time not loading treerings for other dets.
input.tree_rings.only_dets: [R22_S11]

input.opsim_data:
    file_name: ../tests/data/tiny_instcat.txt

#image.nobjects: 5    # (Default is all objects in input file.)
#image.nbatch: 10     # (Default is 10 if using checkpointing, 1 otherwise.)

output.dir: output # default `fits`
