modules:
    - imsim

eval_variables:
    itract: { type: DeepCoaddData, field: tract }
    ipatch: { type: DeepCoaddData, field: patch }
    sband: { type: DeepCoaddData, field: band }

input:
    sky_catalog:
        file_name: default_sky_cat.yaml
        band: $band

    checkpoint:
        dir: checkpoint
        file_name:
          type: FormattedStr
          format : checkpoint_%s-%d-%d.hdf
          items:
              - $band
              - $tract
              - $patch

gal:
    type: SkyCatObj

stamp:
    type: RubinDeepCoadd
    world_pos:
        type: SkyCatWorldPos

image:
    type: RubinDeepCoadd
    random_seed: 42
    nproc: 1
    nbatch: 100
    nsubbatch: 50
    nbatch_fft: 1
    nbatch_per_checkpoint: 1
    band: $band
    tract: $tract
    patch: $patch

    wcs:
        type: RubinDeepCoaddWcs
        band: $band
        tract: $tract
        patch: $patch

    bandpass:
        type: RubinBandpass
        band: $band

psf:
    type: RubinCoaddPSF

output:
   type: RubinDeepCoaddOutput
   coadd_num: 0
   nproc: 1
   nfiles: 1
   dir: fits
   file_name:
       type: FormattedStr
       format: deep_coadd_%s-%d-%d.fits
       items:
           - $band
           - $tract
           - $patch
