# Use baseline configuration
modules:
    - imsim

template: imsim-config

# Use skyCatalogs for obtaining the objects to render.
input.sky_catalog:
    file_name: default_sky_cat.yaml
    band: { type: OpsimData, field: band }
    mjd: { type: OpsimData, field: mjd }

input.opsim_data:
    file_name: default_opsim.db

# Define the galaxy type and positions to use
gal:
    type: SkyCatObj

stamp.world_pos:
    type: SkyCatWorldPos

################################################################
#  Above is template material.
#
#  Make changes below.  Soon you will be able to include the above
#  information via a single template command instead.
################################################################
################################################################

# Put your own commands below here.  For example

# input.sky_catalog.file_name: ../tests/data/sky_cat_9683.yaml
# input.opsim_data.file_name: ../tests/data/small_opsim_9683.db
# input.opsim_data.visit: 449053
# input.tree_rings.only_dets: [R22_S11, R22_S12]
# output.det_num.first: 94
# output.nproc: 2
# output.nfiles: 2
# image.nobjects: 1000
