name: imSim CI

on:
    push:
        branches:
            - main
            - releases/*

    pull_request:
        branches:
            - main
            - releases/*

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ ubuntu-latest ]
                py: [ "3.11" ]
                CC: [ gcc ]
                CXX: [ g++ ]

        defaults:
            run:
                # cf. https://github.com/conda-incubator/setup-miniconda#important
                shell: bash -l {0}

        steps:
            - uses: actions/checkout@v2

            - name: Setup conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: stack
                  python-version: ${{ matrix.py }}
                  condarc-file: etc/.condarc

            - name: Install conda deps
              run: |
                conda update -n base conda
                conda info
                conda list
                conda install -y --file etc/standalone_conda_requirements.txt || true
                conda info
                conda list

            - name: Install skyCatalogs from source
              run: |
                git clone https://github.com/LSSTDESC/skyCatalogs.git
                cd skyCatalogs
                git checkout v1.6.0rc2
                pip install -e .
                cd ..

            - name: Install rubin_sim_data
              run: |
                mkdir rubin_sim_data
                mkdir rubin_sim_data/sims_sed_library
                # Just get the skybrightness, throughputs, and SED data for now.
                curl https://s3df.slac.stanford.edu/groups/rubin/static/sim-data/rubin_sim_data/skybrightness_may_2021.tgz | tar -C rubin_sim_data -xz
                curl https://s3df.slac.stanford.edu/groups/rubin/static/sim-data/rubin_sim_data/throughputs_2023_09_07.tgz | tar -C rubin_sim_data -xz
                curl https://s3df.slac.stanford.edu/groups/rubin/static/sim-data/sed_library/seds_170124.tar.gz  | tar -C rubin_sim_data/sims_sed_library -xz

            - name: Install imSim
              run:
                pip install .

            - name: Install test deps
              run:
                conda install -y pytest nose || true

            - name: Run tests
              run: |
                export RUBIN_SIM_DATA_DIR=`pwd`/rubin_sim_data
                eups list lsst_distrib
                galsim --version
                pytest

            - name: Check example config files
              run: |
                echo $PWD
                ls /home/runner/work/imSim
                export IMSIM_HOME=/home/runner/work/imSim
                export RUBIN_SIM_DATA_DIR=`pwd`/rubin_sim_data
                export SIMS_SED_LIBRARY_DIR=`pwd`/rubin_sim_data/sims_sed_library
                # Just check that they haven't gotten stale and produce errors.
                cd examples
                galsim flat.yaml image.counts_per_pixel=500
                galsim flat_with_sed.yaml image.counts_per_pixel=5
                galsim imsim-user-instcat.yaml image.nobjects=10
                galsim imsim-user-skycat.yaml image.nobjects=10
                galsim imsim-user-instcat-comcam.yaml
                galsim imsim-user-skycat-comcam.yaml
