name: imSim CI

on:
    push:
        branches:
            - main
            - releases/*

    pull_request:
        branches:
            - main
            - releases/*

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                # For now, just ubuntu, 3.8.  Can add more later.
                os: [ ubuntu-latest ]
                py: [ "3.10" ]
                CC: [ gcc ]
                CXX: [ g++ ]

        defaults:
            run:
                # cf. https://github.com/conda-incubator/setup-miniconda#important
                shell: bash -l {0}

        steps:
            - uses: actions/checkout@v2

            - name: Setup conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: stack
                  python-version: ${{ matrix.py }}
                  condarc-file: etc/.condarc

            - name: Install conda deps
              run: |
                conda info
                conda list
                conda install -y mamba
                mamba install -y --file etc/standalone_conda_requirements.txt
                conda info
                conda list

            - name: Install pip deps
              run: |
                pip install skyCatalogs==1.4.0-rc5
                conda info
                conda list

            - name: Install rubin_sim and rubin_sim_data
              run: |
                # Do the minimal installation from source to avoid installing
                # a bunch of unneeded packages.
                git clone https://github.com/lsst/rubin_sim.git
                cd rubin_sim
                git checkout 1.1.1
                pip install -e .
                cd ..
#                mkdir rubin_sim_data
#                mkdir rubin_sim_data/sims_sed_library
                # Just get the skybrightness, throughputs, and SED data for now.
#                curl https://s3df.slac.stanford.edu/groups/rubin/static/sim-data/rubin_sim_data/skybrightness_may_2021.tgz | tar -C rubin_sim_data -xz
#                curl https://s3df.slac.stanford.edu/groups/rubin/static/sim-data/rubin_sim_data/throughputs_aug_2021.tgz | tar -C rubin_sim_data -xz
#                curl https://s3df.slac.stanford.edu/groups/rubin/static/sim-data/sed_library/seds_170124.tar.gz  | tar -C rubin_sim_data/sims_sed_library -xz
		# Temporary fix for USDF downtime. 
                wget --no-check-certificate https://webhome.phy.duke.edu/~cwalter/tmp/sims-data.tar.gz
                tar xzvf sims-data.tar.gz
                rm sims-data.tar.gz
		 
            - name: Install imSim
              run:
                pip install .

            - name: Install test deps
              run:
                conda install -y pytest nose

            - name: Run tests
              run: |
                export RUBIN_SIM_DATA_DIR=`pwd`/rubin_sim_data
                eups list lsst_distrib
                pytest

            - name: Check example config files
              run: |
                export RUBIN_SIM_DATA_DIR=`pwd`/rubin_sim_data
                export SIMS_SED_LIBRARY_DIR=`pwd`/rubin_sim_data/sims_sed_library
                cd config
                # Just check that they haven't gotten stale and produce errors.
                galsim imsim-user.yaml
                galsim flat.yaml image.counts_per_pixel=500
                galsim flat_with_sed.yaml image.counts_per_pixel=5
