name: imSim CI

on:
    push:
        branches:
            - main
            - releases/*

    pull_request:
        branches:
            - main
            - releases/*

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                # For now, just ubuntu, 3.8.  Can add more later.
                os: [ ubuntu-latest ]
                py: [ 3.8 ]
                CC: [ gcc ]
                CXX: [ g++ ]

        defaults:
            run:
                # cf. https://github.com/conda-incubator/setup-miniconda#important
                shell: bash -l {0}

        steps:
            - uses: actions/checkout@v2

            - name: Setup conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: stack
                  python-version: 3.8
                  condarc-file: etc/.condarc

            - name: Install conda deps
              run: |
                conda info
                conda list
                conda install -y mamba
                mamba install -y --file conda_requirements.txt
                conda info
                conda list

            - name: Install pip deps
              run: |
                # We need to get batoid onto conda, but for now, this is a separate step.
                pip install batoid
                conda info
                conda list

            - name: Install imSim
              run:
                pip install .

            - name: Install skyCatalogs
              run: |
                git clone https://github.com/LSSTDESC/skyCatalogs.git
                eups declare skycatalogs -r ${PWD}/skyCatalogs -t current
                setup skycatalogs

            - name: Install test deps
              run:
                conda install -y pytest nose

            - name: Run tests
              run: |
                cd tests
                # We're working towards getting all the tests working, but so far these are
                # the ones that work withe the pip installation.
                pytest test_FWHMgeom.py test_atmPSF.py test_batoid_wcs.py test_cosmic_rays.py test_fopen.py test_instcat_parser.py test_optical_zernikes.py test_psf.py test_tree_rings.py test_trimmer.py
