name: imSim CI

on:
    push:
        branches:
            - main
            - releases/*

    pull_request:
        branches:
            - main
            - releases/*

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                # For now, just ubuntu, 3.8.  Can add more later.
                os: [ ubuntu-latest ]
                py: [ 3.8 ]
                CC: [ gcc ]
                CXX: [ g++ ]

        defaults:
            run:
                # cf. https://github.com/conda-incubator/setup-miniconda#important
                shell: bash -l {0}

        steps:
            - uses: actions/checkout@v2

            - name: Setup conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: stack
                  python-version: 3.8
                  condarc-file: etc/.condarc

            - name: Install conda deps
              run: |
                conda info
                conda list
                conda install -y mamba
                mamba install -y --file etc/standalone_conda_requirements.txt
                conda info
                conda list

            - name: Install pip deps
              run: |
                # We need to get batoid onto conda, but for now, this is a separate step.
                pip install batoid
                pip install skyCatalogs==1.1.0
                conda info
                conda list

            - name: Install rubin_sim and rubin_sim_data
              run: |
                # Do the minimal installation from source to avoid installing
                # a bunch of unneeded packages.
                git clone https://github.com/lsst/rubin_sim.git
                cd rubin_sim
                pip install -e .
                cd ..
                mkdir rubin_sim_data
                # Just get the skybrightness and throughputs data for now.
                curl https://s3df.slac.stanford.edu/groups/rubin/static/sim-data/rubin_sim_data/skybrightness_may_2021.tgz | tar -C rubin_sim_data -xz
                curl https://s3df.slac.stanford.edu/groups/rubin/static/sim-data/rubin_sim_data/throughputs_aug_2021.tgz | tar -C rubin_sim_data -xz

            - name: Install imSim
              run:
                pip install .

            - name: Install test deps
              run:
                conda install -y pytest nose

            - name: Run tests
              run: |
                export RUBIN_SIM_DATA_DIR=`pwd`/rubin_sim_data
                eups list lsst_distrib
                pytest
