# Perform imSim unit tests within the latest imSim docker environment image.

name: imSim CI with docker

on:
  push:
    branches:
      - ci_with_docker
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest

    # Point to the imSim docker image.
    container:
      image: lsstdesc/imsim-env:latest
      options: --user root

    steps:
      # Check out imSim repo
      - uses: actions/checkout@v3

      # Run CI, this all has to be done in a single shell instance.
      # -----------------------------------------------------------
      # 1) Activate LSST stack
      # 2) Install latest version of imSim
      # 3) Install test dependencies
      # 4) Run pytest
      - name: Run imSim unit tests
        run: |
          source /opt/lsst/software/stack/loadLSST.bash
          setup lsst_distrib
          pip install -e .
          conda install -y pytest nose
          pytest
